[package]
name = "avro_to_typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
avro-rs = "0.13"
clap = { version = "4.5", features = ["derive"] }
swc_common = "4.0.1"
swc_ecma_ast = "4.0.1"
swc_ecma_codegen = "4.0.2"
